logo: # add logo name
title: Alex Mabry
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: headshot-mabry.png # your photo
author-name: Alex Mabry # your name
about-author: Graphic and Web Designer # about author
email: alexandramabry1@gmail.com # your email
phone: (402)-560-0011 # your pnone number
website: https://alexmabry.com # you website

# Social link
#google_url:    # add url link
#twitter_url:   # add url link
instagram_url: alexandra_mabry # add url link
pinterest_url: https://www.pinterest.com/smilexitsxalex/ # add url link
#dribbble_url:  # add url link
facebook_url: https://www.facebook.com/alexandra.mabry # add url link

# Disqus
discus_identifier: # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
